//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techwales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_details
    {
        public int Id { get; set; }
        public Nullable<int> uid { get; set; }
        public string Full_Name { get; set; }
        public string Agent_cat { get; set; }
        public string club_details { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public byte[] Proof { get; set; }
        public Nullable<bool> approval { get; set; }
    }
}
