//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techwales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_details
    {
        public int Id { get; set; }
        public Nullable<int> uid { get; set; }
        public string Full_Name { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> shoe { get; set; }
        public string Medical_issues { get; set; }
        public string Injuries { get; set; }
        public string Athletic_history { get; set; }
        public Nullable<double> Weekly_trg { get; set; }
        public string occupation { get; set; }
        public byte[] Proof { get; set; }
        public string why_you { get; set; }
        public string goal { get; set; }
        public Nullable<bool> approval { get; set; }
    }
}
